// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ0K_zK0AHVIFQ9VyPZ8CLE66WR77-tF0',
    appId: '1:996572723666:android:2b66d682ef9bd2dee1b00b',
    messagingSenderId: '996572723666',
    projectId: 'the-fellows-run',
    storageBucket: 'the-fellows-run.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_15O1vbuol7f2cOecUxmeezucdzmwNIM',
    appId: '1:996572723666:ios:c972850b51c83bf3e1b00b',
    messagingSenderId: '996572723666',
    projectId: 'the-fellows-run',
    storageBucket: 'the-fellows-run.firebasestorage.app',
    iosBundleId: 'com.example.theFellowsRun',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-w44q1-M92-NolULpGhyqknwUYiwxRUQ',
    appId: '1:996572723666:web:6b00c0f116e03e37e1b00b',
    messagingSenderId: '996572723666',
    projectId: 'the-fellows-run',
    authDomain: 'the-fellows-run.firebaseapp.com',
    storageBucket: 'the-fellows-run.firebasestorage.app',
  );
}
